application:
  host: 0.0.0.0
database:
  require_ssl: true
email_client:
  base_url: 'https://api.mailgun.net/v3/sandbox2179c580c8784aebaa4dcd0ea6dae6b3.mailgun.org'
  sender_email: 'mailgun@sandbox2179c580c8784aebaa4dcd0ea6dae6b3.mailgun.org'
