name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo to runner
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          # if profile is not set, rustup installs rust-docs, clippy and rustfmt by default
          profile: minimal
          toolchain: stable
          # sets this toolchain as an override for the current directory
          override: true
      - name: Runs specified cargo command
        uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo to runner
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          # sets this toolchain as an override for the current directory
          override: true
      - name: Runs specified cargo command
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          # formats all packages and local path based dependencies
          args: --all -- --check